services:
  mysql:
    image: mysql:9.4.0
    environment:
      MYSQL_ROOT_PASSWORD: devdojo
      MYSQL_USER: luis
      MYSQL_PASSWORD: luis123
    ports:
      - "3306:3306"
    volumes:
      - devdojo-db:/var/lib/mysql

volumes:
  devdojo-db: