spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: anime-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_service?userTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_ROOT_USER}
    password: ${ENV_ROOT_PASSWORD}
  jpa:
    show-sql: true
  threads:
    virtual:
      enabled: true

logging:
  level:
    academy.devdojo: debug
server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param
  tomcat:
    threads:
      max: 20