spring:
  application:
    name: anime-service
  threads:
    virtual:
      enable: true

logging:
  level:
    academy.devdojo: debug
server:
  serverlet:
    context-path: /
  error:
    include-stacktrace: on_param
  tomcate:
    max: 20

database:
  url: ${DB_URL:localhost}:${DB_PORT:3382}
  username: ${LOCAL_USERNAME}
  password: ${LOCAL_PASSWORD}