spring:
  application:
    name: anime-service
  threads:
    virtual:
      enabled: true

logging:
  level:
    academy.devdojo: debug
server:
  port: 8081
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param
  tomcat:
    threads:
      max: 20

database:
  url: ${DB_URL:localhost}:${DB_PORT:3306}
  username: ${LOCAL_USERNAME:luis}
  password: ${LOCAL_PASSWORD:luis123}